//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamagotchiHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tamagotchi : IValidatableObject
    {
        public int Id { get; set; }
        public Nullable<int> HotelKamerID { get; set; }
        public string Naam { get; set; }
        public string Kleur { get; set; }
        public int Leeftijd { get; set; }
        public int Centjes { get; set; }
        public int Level { get; set; }
        public int Gezondheid { get; set; }
        public int Verveling { get; set; }
        public bool Dood { get; set; }

        public virtual HotelKamer HotelKamer { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var pNaam = new[] { "Naam" };

            if (Naam == null || Naam.Length == 0)
            {
                yield return new ValidationResult("Een tamagotchi heeft graag een naam. Anders gaat die huilen", pNaam);
            }

            else if (Naam.Length > 10)
            {
                yield return new ValidationResult("Deze naam is te lang om te onthouden. Vul een naam kleiner dan 10 in.", pNaam);
            }

            if (Verveling > 100)
            {
                Verveling = 100;
            }
            if (Verveling < 0)
            {
                Verveling = 0;
            }

            if (Gezondheid > 100)
            {
                Gezondheid = 100;
            }

            if (Gezondheid <= 0)
            {
                Gezondheid = 0;
                Dood = true;
            }
        }
    }
}
